version: "3"

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  bot:
    build: .
    hostname: bot
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DEBUG=1
    depends_on:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  mongodata:
